#!/bin/bash

day="${1-}"
here="${0%/*}"

[ -n "$day" ] || {
  echo >&2 "Usage: ${0##*/} day"
  exit 1
}
day=${day/day/}
echo "Setting up for day $day..."
target="day$day"

[[ -d "target" ]] || {
  echo "$target already exists!"
  exit 1
}
mkdir -p "$target" || exit 1

sarg="s/dayxx/day$day/; s/day: -1/day: $day/"
sed "$sarg" "$here/skel/index.js" > "$target/index.js"
touch "$target/example.txt" "$target/data.txt"

git add "$target/index.js" "$target/example.txt" "$target/data.txt"

cd "$target" || exit 1
gvim example.txt data.txt
gvim index.js
